In [66]:
import pandas as pd
import datetime as dt

In [67]:
df1=pd.read_csv(r'C:\Users\divya\Desktop\glca\python\weather prediction\datasets\raw_data\train (2).csv')

In [68]:
df2=pd.read_csv(r'C:\Users\divya\Desktop\glca\python\weather prediction\datasets\raw_data\test.csv')

In [69]:
df1

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Cloud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204,14.9569,0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269,15.8263,0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259,15.8263,0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
94263,2016-05-09 19:00:00.000 +0200,Partly Cloudy,rain,19.972222,19.972222,0.40,9.4668,42,16.1000,0,1018.11,Partly cloudy throughout the day.
94264,2016-05-09 20:00:00.000 +0200,Partly Cloudy,rain,17.816667,17.816667,0.46,3.8962,19,15.5526,0,1018.42,Partly cloudy throughout the day.
94265,2016-05-09 21:00:00.000 +0200,Partly Cloudy,rain,13.938889,13.938889,0.67,8.0500,70,16.1000,0,1019.21,Partly cloudy throughout the day.
94266,2016-05-09 22:00:00.000 +0200,Partly Cloudy,rain,12.733333,12.733333,0.77,8.0500,80,16.1000,0,1019.70,Partly cloudy throughout the day.
94267,2016-05-09 23:00:00.000 +0200,Partly Cloudy,rain,13.038889,13.038889,0.69,3.2039,75,15.1823,0,1019.45,Partly cloudy throughout the day.

In [70]:
df2

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Cloud Cover,Pressure (millibars),Daily Summary
0,2016-11-01 00:00:00.000 +0100,Mostly Cloudy,NaN,6.205556,4.527778,0.92,8.1466,297,0.0000,0,1021.74,Partly cloudy starting in the afternoon.
1,2016-11-01 01:00:00.000 +0100,Mostly Cloudy,NaN,5.827778,4.177778,0.92,7.7763,296,0.0000,0,1021.69,Partly cloudy starting in the afternoon.
2,2016-11-01 02:00:00.000 +0100,Partly Cloudy,NaN,5.311111,3.616667,0.93,7.6153,298,0.0000,0,1021.61,Partly cloudy starting in the afternoon.
3,2016-11-01 03:00:00.000 +0100,Partly Cloudy,NaN,4.800000,3.088889,0.94,7.3738,300,0.0000,0,1021.54,Partly cloudy starting in the afternoon.
4,2016-11-01 04:00:00.000 +0100,Clear,NaN,4.483333,2.883333,0.95,6.8103,303,0.0000,0,1021.54,Partly cloudy starting in the afternoon.
...,...,...,...,...,...,...,...,...,...,...,...,...
2180,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31,16.1000,0,1014.36,Partly cloudy starting in the morning.
2181,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20,15.5526,0,1015.16,Partly cloudy starting in the morning.
2182,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30,16.1000,0,1015.66,Partly cloudy starting in the morning.
2183,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20,16.1000,0,1015.95,Partly cloudy starting in the morning.
2184,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39,15.5204,0,1016.16,Partly cloudy starting in the morning.

In [71]:
df1.isnull().sum()

Formatted Date                0
Summary                       0
Precip Type                 143
Temperature (C)               0
Apparent Temperature (C)      0
Humidity                      0
Wind Speed (km/h)             0
Wind Bearing (degrees)        0
Visibility (km)               0
Cloud Cover                   0
Pressure (millibars)          0
Daily Summary                 0
dtype: int64

In [72]:
data=pd.concat([df1,df2],axis=0)

In [73]:
data

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Cloud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204,14.9569,0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269,15.8263,0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259,15.8263,0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
2180,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31,16.1000,0,1014.36,Partly cloudy starting in the morning.
2181,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20,15.5526,0,1015.16,Partly cloudy starting in the morning.
2182,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30,16.1000,0,1015.66,Partly cloudy starting in the morning.
2183,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20,16.1000,0,1015.95,Partly cloudy starting in the morning.
2184,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39,15.5204,0,1016.16,Partly cloudy starting in the morning.

In [74]:
data.isnull().sum()

Formatted Date                0
Summary                       0
Precip Type                 517
Temperature (C)               0
Apparent Temperature (C)      0
Humidity                      0
Wind Speed (km/h)             0
Wind Bearing (degrees)        0
Visibility (km)               0
Cloud Cover                   0
Pressure (millibars)          0
Daily Summary                 0
dtype: int64

In [75]:
data.reset_index(inplace=True)

In [76]:
data

,index,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Cloud Cover,Pressure (millibars),Daily Summary
0,0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.
1,1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.
2,2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204,14.9569,0,1015.94,Partly cloudy throughout the day.
3,3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269,15.8263,0,1016.41,Partly cloudy throughout the day.
4,4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259,15.8263,0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2180,2016-09-09 19:00:00.000 +0200,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31,16.1000,0,1014.36,Partly cloudy starting in the morning.
96449,2181,2016-09-09 20:00:00.000 +0200,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20,15.5526,0,1015.16,Partly cloudy starting in the morning.
96450,2182,2016-09-09 21:00:00.000 +0200,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30,16.1000,0,1015.66,Partly cloudy starting in the morning.
96451,2183,2016-09-09 22:00:00.000 +0200,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20,16.1000,0,1015.95,Partly cloudy starting in the morning.
96452,2184,2016-09-09 23:00:00.000 +0200,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39,15.5204,0,1016.16,Partly cloudy starting in the morning.

In [77]:
data['Precip Type'].mode()

0    rain
Name: Precip Type, dtype: object

In [78]:
data['Precip Type']=data['Precip Type'].fillna(data['Precip Type'].mode())

In [79]:
data[data['Precip Type'].isnull()]

,index,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Cloud Cover,Pressure (millibars),Daily Summary
52672,52672,2012-04-11 16:00:00.000 +0200,Mostly Cloudy,NaN,19.016667,19.016667,0.26,14.8764,163,9.982,0,1002.40,Mostly cloudy until night.
52674,52674,2012-04-11 18:00:00.000 +0200,Mostly Cloudy,NaN,17.850000,17.850000,0.28,13.7977,169,9.982,0,1001.79,Mostly cloudy until night.
52675,52675,2012-04-11 19:00:00.000 +0200,Mostly Cloudy,NaN,16.322222,16.322222,0.32,10.8192,151,9.982,0,1001.60,Mostly cloudy until night.
52677,52677,2012-04-11 21:00:00.000 +0200,Mostly Cloudy,NaN,12.566667,12.566667,0.43,9.0160,159,9.982,0,1001.92,Mostly cloudy until night.
52678,52678,2012-04-11 22:00:00.000 +0200,Mostly Cloudy,NaN,12.927778,12.927778,0.47,17.6295,197,16.100,0,1002.20,Mostly cloudy until night.
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95584,1316,2016-10-31 19:00:00.000 +0100,Mostly Cloudy,NaN,8.322222,7.044444,0.85,8.0339,290,0.000,0,1021.73,Mostly cloudy starting in the afternoon.
95585,1317,2016-10-31 20:00:00.000 +0100,Mostly Cloudy,NaN,7.627778,6.183333,0.87,8.2271,293,0.000,0,1021.76,Mostly cloudy starting in the afternoon.
95586,1318,2016-10-31 21:00:00.000 +0100,Mostly Cloudy,NaN,7.111111,5.511111,0.89,8.5008,297,0.000,0,1021.81,Mostly cloudy starting in the afternoon.
95587,1319,2016-10-31 22:00:00.000 +0100,Partly Cloudy,NaN,6.672222,4.961111,0.90,8.6457,299,0.000,0,1021.83,Mostly cloudy starting in the afternoon.
95588,1320,2016-10-31 23:00:00.000 +0100,Mostly Cloudy,NaN,6.322222,4.588889,0.91,8.4686,299,0.000,0,1021.80,Mostly cloudy starting in the afternoon.

In [80]:
data['Precip Type'].loc[data['Precip Type'].isnull()]=data['Precip Type'].mode()[0]

C:\Users\divya\AppData\Local\Temp\ipykernel_1368\3116929597.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Precip Type'].loc[data['Precip Type'].isnull()]=data['Precip Type'].mode()[0]

In [81]:
data.isnull().sum()

index                       0
Formatted Date              0
Summary                     0
Precip Type                 0
Temperature (C)             0
Apparent Temperature (C)    0
Humidity                    0
Wind Speed (km/h)           0
Wind Bearing (degrees)      0
Visibility (km)             0
Cloud Cover                 0
Pressure (millibars)        0
Daily Summary               0
dtype: int64

In [82]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96453 entries, 0 to 96452
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   index                     96453 non-null  int64
 1   Formatted Date            96453 non-null  object
 2   Summary                   96453 non-null  object
 3   Precip Type               96453 non-null  object
 4   Temperature (C)           96453 non-null  float64
 5   Apparent Temperature (C)  96453 non-null  float64
 6   Humidity                  96453 non-null  float64
 7   Wind Speed (km/h)         96453 non-null  float64
 8   Wind Bearing (degrees)    96453 non-null  int64
 9   Visibility (km)           96453 non-null  float64
 10  Cloud Cover               96453 non-null  int64
 11  Pressure (millibars)      96453 non-null  float64
 12  Daily Summary             96453 non-null  object
dtypes: float64(6), int64(3), object(4)
memory usage: 9.6+ MB

In [83]:
data['Formatted Date']=pd.to_datetime(data['Formatted Date'],utc=True)

In [84]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96453 entries, 0 to 96452
Data columns (total 13 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   index                     96453 non-null  int64
 1   Formatted Date            96453 non-null  datetime64[ns, UTC]
 2   Summary                   96453 non-null  object
 3   Precip Type               96453 non-null  object
 4   Temperature (C)           96453 non-null  float64
 5   Apparent Temperature (C)  96453 non-null  float64
 6   Humidity                  96453 non-null  float64
 7   Wind Speed (km/h)         96453 non-null  float64
 8   Wind Bearing (degrees)    96453 non-null  int64
 9   Visibility (km)           96453 non-null  float64
 10  Cloud Cover               96453 non-null  int64
 11  Pressure (millibars)      96453 non-null  float64
 12  Daily Summary             96453 non-null  object
dtypes: datetime64[ns, UTC](1), float64(6), int64(3), object(3)
memory usage: 9.6+ MB

In [85]:
data.drop(['index'],axis=1,inplace=True)

In [86]:
data['Year']=data['Formatted Date'].dt.year

In [87]:
data['Month_name']=data['Formatted Date'].dt.month_name()

In [88]:
data['day']=data['Formatted Date'].dt.day

In [89]:
data['month']=data['Formatted Date'].dt.month

In [90]:
data

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Cloud Cover,Pressure (millibars),Daily Summary,Year,Month_name,day,month
0,2006-03-31 22:00:00+00:00,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.,2006,March,31,3
1,2006-03-31 23:00:00+00:00,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.,2006,March,31,3
2,2006-04-01 00:00:00+00:00,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204,14.9569,0,1015.94,Partly cloudy throughout the day.,2006,April,1,4
3,2006-04-01 01:00:00+00:00,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269,15.8263,0,1016.41,Partly cloudy throughout the day.,2006,April,1,4
4,2006-04-01 02:00:00+00:00,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259,15.8263,0,1016.51,Partly cloudy throughout the day.,2006,April,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 17:00:00+00:00,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31,16.1000,0,1014.36,Partly cloudy starting in the morning.,2016,September,9,9
96449,2016-09-09 18:00:00+00:00,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20,15.5526,0,1015.16,Partly cloudy starting in the morning.,2016,September,9,9
96450,2016-09-09 19:00:00+00:00,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30,16.1000,0,1015.66,Partly cloudy starting in the morning.,2016,September,9,9
96451,2016-09-09 20:00:00+00:00,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20,16.1000,0,1015.95,Partly cloudy starting in the morning.,2016,September,9,9
96452,2016-09-09 21:00:00+00:00,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39,15.5204,0,1016.16,Partly cloudy starting in the morning.,2016,September,9,9

In [91]:
data.to_csv('Analysis.csv',index=False)

In [92]:
len(data['Daily Summary'].unique())

214

In [93]:
data['Daily Summary'].value_counts()

Daily Summary
Mostly cloudy throughout the day.                                                                       20085
Partly cloudy throughout the day.                                                                        9981
Partly cloudy until night.                                                                               6169
Partly cloudy starting in the morning.                                                                   5184
Foggy in the morning.                                                                                    4201
                                                                                                        ...
Breezy starting overnight continuing until morning and foggy overnight.                                    24
Mostly cloudy throughout the day and breezy starting overnight continuing until afternoon.                 24
Partly cloudy starting in the morning and breezy starting in the afternoon continuing until evening.       24
Rain until afternoon.                                                                                      24
Foggy starting overnight continuing until morning and breezy in the afternoon.                             23
Name: count, Length: 214, dtype: int64

In [94]:
y=data['Daily Summary']

In [95]:
from sklearn.preprocessing import LabelEncoder

In [96]:
le=LabelEncoder()

In [105]:
data['Precip_encoder']=le.fit_transform(data['Precip Type'])

In [106]:
data['Summary_encoder']=le.fit_transform(data['Summary'])

In [107]:
data['Daily Summary_encoder']=le.fit_transform(data['Daily Summary'])

In [100]:
y

0             Partly cloudy throughout the day.
1             Partly cloudy throughout the day.
2             Partly cloudy throughout the day.
3             Partly cloudy throughout the day.
4             Partly cloudy throughout the day.
                          ...
96448    Partly cloudy starting in the morning.
96449    Partly cloudy starting in the morning.
96450    Partly cloudy starting in the morning.
96451    Partly cloudy starting in the morning.
96452    Partly cloudy starting in the morning.
Name: Daily Summary, Length: 96453, dtype: object

In [108]:
data

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Cloud Cover,Pressure (millibars),Daily Summary,Year,Month_name,day,month,Precip_encoder,Summary_encoder,Daily Summary_encoder
0,2006-03-31 22:00:00+00:00,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,0,1015.13,Partly cloudy throughout the day.,2006,March,31,3,0,19,197
1,2006-03-31 23:00:00+00:00,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,0,1015.63,Partly cloudy throughout the day.,2006,March,31,3,0,19,197
2,2006-04-01 00:00:00+00:00,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204,14.9569,0,1015.94,Partly cloudy throughout the day.,2006,April,1,4,0,17,197
3,2006-04-01 01:00:00+00:00,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269,15.8263,0,1016.41,Partly cloudy throughout the day.,2006,April,1,4,0,19,197
4,2006-04-01 02:00:00+00:00,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259,15.8263,0,1016.51,Partly cloudy throughout the day.,2006,April,1,4,0,17,197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96448,2016-09-09 17:00:00+00:00,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31,16.1000,0,1014.36,Partly cloudy starting in the morning.,2016,September,9,9,0,19,170
96449,2016-09-09 18:00:00+00:00,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20,15.5526,0,1015.16,Partly cloudy starting in the morning.,2016,September,9,9,0,19,170
96450,2016-09-09 19:00:00+00:00,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30,16.1000,0,1015.66,Partly cloudy starting in the morning.,2016,September,9,9,0,19,170
96451,2016-09-09 20:00:00+00:00,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20,16.1000,0,1015.95,Partly cloudy starting in the morning.,2016,September,9,9,0,19,170
96452,2016-09-09 21:00:00+00:00,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39,15.5204,0,1016.16,Partly cloudy starting in the morning.,2016,September,9,9,0,19,170

In [102]:
x=data.drop(['Formatted Date','Cloud Cover','Daily Summary','Month_name'],axis=1)

In [104]:
x

,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Pressure (millibars),Year,day,month
0,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251,15.8263,1015.13,2006,31,3
1,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259,15.8263,1015.63,2006,31,3
2,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204,14.9569,1015.94,2006,1,4
3,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269,15.8263,1016.41,2006,1,4
4,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259,15.8263,1016.51,2006,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...
96448,Partly Cloudy,rain,26.016667,26.016667,0.43,10.9963,31,16.1000,1014.36,2016,9,9
96449,Partly Cloudy,rain,24.583333,24.583333,0.48,10.0947,20,15.5526,1015.16,2016,9,9
96450,Partly Cloudy,rain,22.038889,22.038889,0.56,8.9838,30,16.1000,1015.66,2016,9,9
96451,Partly Cloudy,rain,21.522222,21.522222,0.60,10.5294,20,16.1000,1015.95,2016,9,9
96452,Partly Cloudy,rain,20.438889,20.438889,0.61,5.8765,39,15.5204,1016.16,2016,9,9

In [109]:
data.to_csv('weatherml.csv',index=False)